### ISSUE TITLE
[ documentation ] Taskfile as an alternative to Ninja

### ISSUE THREAD

**Issue by yonas** [ruuda/rcl#61]
Doc page: https://docs.ruuda.nl/rcl/using_ninja/

[Task](https://github.com/go-task/task) is a lot easier than Ninja. Here's an [example](https://taskfile.dev/usage/#prevent-unnecessary-work):

### Prevent unnecessary work
By fingerprinting locally generated files and their sources

If a task generates something, you can inform Task the source and generated files, so Task will prevent running them if not necessary.

```yaml
version: '3'

tasks:
  build:
    deps: [js, css]
    cmds:
      - go build -v -i main.go

  js:
    cmds:
      - esbuild --bundle --minify js/index.js > public/bundle.js
    sources:
      - src/js/**/*.js
    generates:
      - public/bundle.js

  css:
    cmds:
      - esbuild --bundle --minify css/index.css > public/bundle.css
    sources:
      - src/css/**/*.css
    generates:
      - public/bundle.css
```
